/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-26 00:44:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.lecture;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class en_005flec_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/teamB-project/WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1669102095569L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>design_test_ver4</title>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("#container {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#container2 {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_wrap {\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	height: 350px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_wrap2 {\r\n");
      out.write("	width: 980px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".pm_detail_top {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_detail_top .img {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 40%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_detail_top .img img {\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 340px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lecture {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 60%;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	padding: 50px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icons {\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lecture h2 {\r\n");
      out.write("	color: #222;\r\n");
      out.write("	font-size: 26px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	padding-right: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lecture .name {\r\n");
      out.write("	margin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lecture .name>strong {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	color: #222;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lecture .name>span {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lecture .name .btn {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	width: 24px;\r\n");
      out.write("	height: 24px;\r\n");
      out.write("	background-color: #1988cc;\r\n");
      out.write("	background-size: 16px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lecture .btns a {\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 170px;\r\n");
      out.write("	height: 60px;\r\n");
      out.write("	line-height: 60px;\r\n");
      out.write("	border: 1px solid #e84c4c;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	background-color: #e84c4c;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	padding: 0 15px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	transition: all 0.15s;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".en_table table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".en_table table tbody tr {\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".en_table table tbody tr th {\r\n");
      out.write("	background-color: #000;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".en_table table tbody tr td {\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	padding: 15px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".en_progress {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".en_bar {\r\n");
      out.write("	background-color: #ff612a;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	height: 16px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".en_bar .data {\r\n");
      out.write("	background-color: #0179b6;\r\n");
      out.write("	height: 16px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".percent {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	top: 22px;\r\n");
      out.write("	line-height: 1.3;\r\n");
      out.write("	color: #222;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".percent.p1 {\r\n");
      out.write("	left: 0;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".percent.p2 {\r\n");
      out.write("	right: 0;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_tabs_view {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	margin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_tabs_view ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_tabs_view li {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 16.66666%;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-bottom: 1px solid #e84c4c;\r\n");
      out.write("	background-color: #f3f3f3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_tabs_view li.on {\r\n");
      out.write("	border: 1px solid #e84c4c;\r\n");
      out.write("	border-top-width: 5px;\r\n");
      out.write("	border-bottom: none;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_tabs_view li.on a {\r\n");
      out.write("	color: #222;\r\n");
      out.write("	height: 46px;\r\n");
      out.write("	line-height: 46px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_tabs_view a {\r\n");
      out.write("	color: #555;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	height: 48px;\r\n");
      out.write("	line-height: 48px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pmLectContent {\r\n");
      out.write("	padding: 50px 20px 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_view_section .tit {\r\n");
      out.write("	font-size: 26px;\r\n");
      out.write("	color: #222;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_view_section .tit b {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_view_section .tit span {\r\n");
      out.write("	color: #bbb;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_view_section .tit:after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 0;\r\n");
      out.write("	border-bottom: 4px dotted #eee;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 140px;\r\n");
      out.write("	top: 17px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_view_section .cont {\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	color: #777;\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("	padding: 0 0 0 170px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	min-height: 120px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pm_view_section .cont+.tit {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<div class=\"main_wrap\">\r\n");
      out.write("			<div class=\"sub_wrap\">\r\n");
      out.write("				<div class=\"pm_detail_top\">\r\n");
      out.write("					<div class=\"img\">\r\n");
      out.write("						<img src=\"img/teacher/teacher1.png\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"lecture\">\r\n");
      out.write("						<div class=\"icons\">\r\n");
      out.write("							<i class=\"pmico yellow\">중학2</i> <i class=\"pmico blue\">내신기본</i> <i\r\n");
      out.write("								class=\"pmico sky\">완강</i> <i class=\"pmico green\">교재</i>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h2>[중2] 싸플 중학 과학</h2>\r\n");
      out.write("						<div class=\"name\">\r\n");
      out.write("							<strong>김청해</strong> <span>선생님</span> <a href=\"#선생님정보\"\r\n");
      out.write("								class=\"btn\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"btns\">\r\n");
      out.write("							<a class=\"btn1\">수강신청</a> <a class=\"btn1\">교재구매</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"container2\">\r\n");
      out.write("		<div class=\"main_wrap2\">\r\n");
      out.write("			<div class=\"en_table\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>수강대상</th>\r\n");
      out.write("						<td>중학2/내신기본</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>수강기간</th>\r\n");
      out.write("						<td>151강/총180일</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>강의교재</th>\r\n");
      out.write("						<td>씨플 중학교 과학 2</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>강좌구성</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<div class=\"en_progress\">\r\n");
      out.write("								<div class=\"en_bar\">\r\n");
      out.write("									<div class=\"data\" style=\"width: 30%\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"percent p1\">\r\n");
      out.write("									<strong>30%</strong> <span>개념설명</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"percent p2\">\r\n");
      out.write("									<strong>70%</strong> <span>문제풀이</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"container2\">\r\n");
      out.write("		<div class=\"main_wrap2\">\r\n");
      out.write("			<div class=\"pm_tabs_view\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"on\"><a>강의소개</a></li>\r\n");
      out.write("					<li><a>강의목록</a></li>\r\n");
      out.write("					<li><a>공지사항</a></li>\r\n");
      out.write("					<li><a>학습Q/A</a></li>\r\n");
      out.write("					<li><a>수강후기</a></li>\r\n");
      out.write("					<li><a>자료실</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"pm_view_section\" id=\"pmLectContent\">\r\n");
      out.write("				<div class=\"tit\">\r\n");
      out.write("					<b> 강의 범위 <span>lecture scope</span>\r\n");
      out.write("					</b>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"cont\">\r\n");
      out.write("					싸플 중학교 과학2 <br> 1. 물질의 구성 <br> 2. 전기와 자기 <br> 3. 태양계\r\n");
      out.write("					<br> 4. 식물과 에너지 <br> 5. 동물과 에너지\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"tit\">\r\n");
      out.write("					<b> 수강대상 <span>lecture target</span>\r\n");
      out.write("					</b>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"cont\">\r\n");
      out.write("					- 중학교 2학년 과학을 체계적으로 학습하고자 하는 학생 <br> - 과학의 기초가 없어 중학교 과학이 어려운\r\n");
      out.write("					학생 <br> - 수행평가 및 지필고사를 완벽하게 대비하고자 하는 학생\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
