/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-25 07:38:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.lecture;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class exam_005fquestion_005fnew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/teamB-project/WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1669102095569L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h3>문제 추가</h3>\r\n");
      out.write("	<div id=\"container py-5\">\r\n");
      out.write("		<div class=\"col-lg-7 mx-auto bg-white rounded shadow\" id='asd'>\r\n");
      out.write("		\r\n");
      out.write("			<form method='post' action='notice_write' enctype='multipart/form-data'>\r\n");
      out.write("\r\n");
      out.write("				<input type=\"radio\" class=\"btn-check\" name='exam' id='multiple' checked>  <label class=\"btn btn-outline-danger\" for=\"multiple\">객관식</label>\r\n");
      out.write("				<input type=\"radio\" class=\"btn-check\" name='exam' id='short'>  <label class=\"btn btn-outline-danger\" for=\"short\">주관식</label>\r\n");
      out.write("				<table class=\"table\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th class=\"col-3 align-middle px-4 py-3\">문제제목</th>\r\n");
      out.write("						<td class=\"align-middle\"><input class='form-control' type=\"text\"  name='title'></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th class=\"col-3 align-middle px-4 py-3\">문제내용</th>\r\n");
      out.write("						\r\n");
      out.write("						<td class=\"align-middle\">\r\n");
      out.write("							<textarea class=\"form-control px-4 py-3\" style=\"height:100px\" name='content'></textarea>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr class='select_mutiple'>\r\n");
      out.write("						<th class=\"col-3 align-middle px-4 py-3\">1번 지문</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<textarea class=\"form-control px-4 py-3\" style=\"height:100px\" name='select1'></textarea>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("					<tr class='select_mutiple'>\r\n");
      out.write("						<th class=\"col-3 align-middle px-4 py-3\">2번 지문</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<textarea class=\"form-control px-4 py-3\" style=\"height:100px\" name='select2'></textarea>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("					<tr class ='select_mutiple'>\r\n");
      out.write("						<th class=\"col-3 align-middle px-4 py-3\">3번 지문</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<textarea class=\"form-control px-4 py-3\" style=\"height:100px\" name='select3'></textarea>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("					<tr class='select_mutiple'>\r\n");
      out.write("						<th class=\"col-3 align-middle px-4 py-3\">4번 지문</th>\r\n");
      out.write("						<td>\r\n");
      out.write("							<textarea class=\"form-control px-4 py-3\" style=\"height:100px\" name='select4'></textarea>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th class=\"col-3 align-middle px-4 py-3\">문제점수</th>\r\n");
      out.write("						<td class=\"align-middle\"  style=\"float:left\"><input type=\"text\"  name='score'></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("				<button type=\"button\" class='btnAdd'>문제추가하기</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("	$(function (){\r\n");
      out.write("		 \r\n");
      out.write("		$('input[type=\"radio\"]').on('click', function(){\r\n");
      out.write("		  var chkValue = $('input[type=radio][id=\"multiple\"]:checked').val();\r\n");
      out.write("		  if(chkValue){\r\n");
      out.write("			  $('.select_mutiple').css('display','');\r\n");
      out.write("		  }else{\r\n");
      out.write("			  $('.select_mutiple').css('display','none');     \r\n");
      out.write("		  }\r\n");
      out.write("		 \r\n");
      out.write("		});\r\n");
      out.write("		 \r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	 $(function() {\r\n");
      out.write("	        $(\".btnAdd\").on(\"click\", function() {\r\n");
      out.write("	            $(\".table\").clone().appendTo(\"#asd\");\r\n");
      out.write("	        })\r\n");
      out.write("	    })\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
