/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-26 00:43:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.lecture;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gallery_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>lec_list_test</title>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"css/member.css?");
      out.print(new java.util.Date());
      out.write("\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\r\n");
      out.write("<style>\r\n");
      out.write(".enrolment_lecture_box {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	max-width: 1200px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tb_top {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list_top1 {\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	float: left;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search_select {\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list_top2, .list_top3 {\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	float: right;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_sort {\r\n");
      out.write("	float: right;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_sort>span {\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("	font-size: 35px;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list_top3>span>input[type=\"text\"] {\r\n");
      out.write("	height: 50px !important;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_search {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".boxes {\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	height: 330px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile_card {\r\n");
      out.write("	width: 280px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cards-container {\r\n");
      out.write("	width: 280px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	box-shadow: 0px 1px 2px 1px #000;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".upper-container {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	background: #7F00FF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lower-container {\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	background: #FFF;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lower-container>div {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lower-container h6 {\r\n");
      out.write("	color: #7F00FF;\r\n");
      out.write("	opacity: .6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lower-container>div>img {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lower-container .btn {\r\n");
      out.write("	padding: 12px 20px;\r\n");
      out.write("	background: #7F00FF;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	transition: all .3s ease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lower-container .btn:hover {\r\n");
      out.write("	background: transparent;\r\n");
      out.write("	color: #7F00FF;\r\n");
      out.write("	border: 2px solid #7F00FF;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"container\" class=\"ct_top\">\r\n");
      out.write("		<div class=\"main_wrap\">\r\n");
      out.write("			<h2 class=\"lnb_title text-center text-dark\">강의 목록</h2>\r\n");
      out.write("			<div id=\"contet_area\">\r\n");
      out.write("				<div class=\"content_body\">\r\n");
      out.write("					<div class=\"enrolment_lecture_box\">\r\n");
      out.write("						<div class=\"tb_top\">\r\n");
      out.write("							<div class=\"list_top1\">\r\n");
      out.write("								<select class=\"search_select\" name=\"scid\">\r\n");
      out.write("									<option>전체</option>\r\n");
      out.write("									<option>국어</option>\r\n");
      out.write("									<option>수학</option>\r\n");
      out.write("									<option>영어</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"list_top3\">\r\n");
      out.write("								<span> <select class=\"search_select\" name=\"s_field\">\r\n");
      out.write("										<option>전체</option>\r\n");
      out.write("										<option>과정명</option>\r\n");
      out.write("										<option>과정내용</option>\r\n");
      out.write("								</select>\r\n");
      out.write("								</span> <span> <input type=\"text\">\r\n");
      out.write("								</span> <span> <a href=\"#\"\r\n");
      out.write("									class=\"btn btn-dark text-white btn_search\">검색</a>\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"list_top2\">\r\n");
      out.write("								<div class=\"btn_sort\">\r\n");
      out.write("									<span class=\"material-symbols-outlined\"><a\r\n");
      out.write("										href=\"gallery_list.le\">gallery_thumbnail</a></span> <span\r\n");
      out.write("										class=\"material-symbols-outlined\"><a\r\n");
      out.write("										href=\"just_list.le\">list_alt</a></span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"boxes\">\r\n");
      out.write("							<div class=\"profile_card\">\r\n");
      out.write("								<div class=\"cards\">\r\n");
      out.write("									<div class=\"cards-container\">\r\n");
      out.write("										<div class=\"upper-container\"></div>\r\n");
      out.write("										<div class=\"lower-container\">\r\n");
      out.write("											<div>\r\n");
      out.write("												<h6>귀에 쏙 꽂히는 영어강의 No.1!!!</h6>\r\n");
      out.write("												<h4>주혜연 선생님</h4>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div>\r\n");
      out.write("												<img src=\"img/teacher/et01.png\">\r\n");
      out.write("											</div>\r\n");
      out.write("											<div>\r\n");
      out.write("												<a href=\"en_lec_detail.le\" class=\"btn\">수강신청</a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"profile_card\">\r\n");
      out.write("								<div class=\"cards\">\r\n");
      out.write("									<div class=\"cards-container\">\r\n");
      out.write("										<div class=\"upper-container\"></div>\r\n");
      out.write("										<div class=\"lower-container\">\r\n");
      out.write("											<div>\r\n");
      out.write("												<h6>모든 유형의 영어 마스터 허준석</h6>\r\n");
      out.write("												<h4>허준석 선생님</h4>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div>\r\n");
      out.write("												<img src=\"img/teacher/et02.png\">\r\n");
      out.write("											</div>\r\n");
      out.write("											<div>\r\n");
      out.write("												<a href=\"#\" class=\"btn\">수강신청</a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"profile_card\">\r\n");
      out.write("								<div class=\"cards\">\r\n");
      out.write("									<div class=\"cards-container\">\r\n");
      out.write("										<div class=\"upper-container\"></div>\r\n");
      out.write("										<div class=\"lower-container\">\r\n");
      out.write("											<div>\r\n");
      out.write("												<h6>최고의 영어 강의를 보라!</h6>\r\n");
      out.write("												<h4>김보라 선생님</h4>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div>\r\n");
      out.write("												<img src=\"img/teacher/et01.png\">\r\n");
      out.write("											</div>\r\n");
      out.write("											<div>\r\n");
      out.write("												<a href=\"#\" class=\"btn\">수강신청</a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"profile_card\">\r\n");
      out.write("								<div class=\"cards\">\r\n");
      out.write("									<div class=\"cards-container\">\r\n");
      out.write("										<div class=\"upper-container\"></div>\r\n");
      out.write("										<div class=\"lower-container\">\r\n");
      out.write("											<div>\r\n");
      out.write("												<h6>승리는 너의 것, 디렉터 황</h6>\r\n");
      out.write("												<h4>황혜경 선생님</h4>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div>\r\n");
      out.write("												<img src=\"img/teacher/et01.png\">\r\n");
      out.write("											</div>\r\n");
      out.write("											<div>\r\n");
      out.write("												<a href=\"#\" class=\"btn\">수강신청</a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
