/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-26 01:35:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.lecture;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lecture_005fhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/teamB-project/WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1669102095569L));
    _jspx_dependants.put("/WEB-INF/views/lecture/../include/sidebar.jsp", Long.valueOf(1674696945080L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/table.css\" rel=\"stylesheet\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<main>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-12\">\r\n");
      out.write("<div class=\"top-breadcrumb\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"img\" style=\"    background-image: linear-gradient(150deg, rgba(63, 174, 255, .3)15%, rgba(63, 174, 255, .3)70%, rgba(63, 174, 255, .3)94%), url(https://bootdey.com/img/Content/flores-amarillas-wallpaper.jpeg);height: 350px;background-size: cover;\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card social-prof\">\r\n");
      out.write("<div class=\"card-body\">\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("<h1 class='mb-5'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecture_info.lecture_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecture_info.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("<p>Web Developer</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row \">\r\n");
      out.write("<div class=\"col-lg-12\">\r\n");
      out.write("<ul class=\" nav nav-tabs justify-content-center s-nav\">\r\n");
      out.write("<li><a class=\"active\" href=\"#\">Timeline</a></li>\r\n");
      out.write("<li><a href=\"#\">About</a></li>\r\n");
      out.write("<li><a href=\"#\">Friends</a></li>\r\n");
      out.write("<li><a href=\"#\">Photos</a></li>\r\n");
      out.write("<li><a href=\"#\">Videos</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-lg-3\">\r\n");
      out.write("<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<style>\r\n");
      out.write("		.profile-card{\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  min-height: 90px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  margin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card img.profile-photo{\r\n");
      out.write("  border: 7px solid #fff;\r\n");
      out.write("  float: left;\r\n");
      out.write("  margin-right: 20px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  top: -30px;\r\n");
      out.write("  height: 70px;\r\n");
      out.write("  width: 70px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card h5 a{\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card a{\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*Newsfeed Links CSS*/\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed{\r\n");
      out.write("  padding-left: 20px;\r\n");
      out.write("  padding-right: 20px;\r\n");
      out.write("  margin: 0 0 40px 0;\r\n");
      out.write("    background:#fff;\r\n");
      out.write("  padding-top:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed li{\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  display: block;\r\n");
      out.write("  padding: 15px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed li div{\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin-left: 30px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed li div::after{\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 1px;\r\n");
      out.write("  border-top: 1px solid #f1f2f2;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: -15px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed li a{color: #6d6e71;}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed li i{\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  margin-right: 15px;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed i.icon1{color: #8dc63f;}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed i.icon2{color: #662d91;}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed i.icon3{color: #ee2a7b;}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-fee i.icon4{color: #f7941e;}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-fee i.con5{color: #1c75bc;}\r\n");
      out.write("\r\n");
      out.write("ul.nav-news-feed i.icon6{color: #9e1f63;}\r\n");
      out.write("\r\n");
      out.write("/*Chat Block CSS*/\r\n");
      out.write("\r\n");
      out.write("#chat-block{\r\n");
      out.write("  margin: 0 0 40px 0;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  background:#fff;\r\n");
      out.write("  padding-top:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#chat-block .title{\r\n");
      out.write("  background: #8dc63f;\r\n");
      out.write("  padding: 2px 20px;\r\n");
      out.write("  width: 70%;\r\n");
      out.write("  height: 30px;\r\n");
      out.write("  border-radius: 15px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin: 0 auto 20px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.online-users{\r\n");
      out.write("  padding-left: 20px;\r\n");
      out.write("  padding-right: 20px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.online-users li{\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin: 3px auto !important;\r\n");
      out.write("  padding-left: 2px;\r\n");
      out.write("  padding-right: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.online-users li span.online-dot{\r\n");
      out.write("  background: linear-gradient(to bottom, rgba(141,198,63, 1), rgba(0,148,68, 1));\r\n");
      out.write("  border: none;\r\n");
      out.write("  height: 12px;\r\n");
      out.write("  width: 12px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: -6px;\r\n");
      out.write("  border: 2px solid #fff;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.profile-photo {\r\n");
      out.write("    height: 58px;\r\n");
      out.write("    width: 58px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.online-users {\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    padding-right: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-inline {\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("    margin-left: -5px;\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-inline>li {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding-right: 5px;\r\n");
      out.write("    padding-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-white {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <div class=\"col-md-4 static\">\r\n");
      out.write("            <div class=\"profile-card\">\r\n");
      out.write("    <ul class=\"nav-news-feed\">\r\n");
      out.write("              <li><i class=\"fa fa-list-alt icon1\"></i><div><a href=\"/web/notice_list.le?lecture_code=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecture_info.lecture_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\">My Newsfeed</a></div></li>\r\n");
      out.write("              <li><i class=\"fa fa-users icon2\"></i><div><a href=\"#\">People Nearby</a></div></li>\r\n");
      out.write("              <li><i class=\"fa fa-user icon3\"></i><div><a href=\"#\">Friends</a></div></li>\r\n");
      out.write("              <li><i class=\"fa fa-comments icon4\"></i><div><a href=\"#\">Messages</a></div></li>\r\n");
      out.write("              <li><i class=\"fa fa-picture-o icon5\"></i><div><a href=\"#\">Images</a></div></li>\r\n");
      out.write("              <li><i class=\"fa fa-video-camera icon6\"></i><div><a href=\"#\">Videos</a></div></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/*social */\r\n");
      out.write(".card-one {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 300px;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    box-shadow: 0 10px 7px -5px rgba(0, 0, 0, 0.4);\r\n");
      out.write("}\r\n");
      out.write(".card {\r\n");
      out.write("    margin-bottom: 35px;\r\n");
      out.write("    box-shadow: 0 10px 20px 0 rgba(26, 44, 57, 0.14);\r\n");
      out.write("    border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".follower-wrapper li {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-profile {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-profile a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-profile {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-bottom: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-profile .user-profile {\r\n");
      out.write("\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: -75px;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    height: 150px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-nav {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-prof {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-prof .wrapper {\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    margin-top: -200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-prof img {\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    height: 150px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    border: 5px solid #fff;\r\n");
      out.write("    /*border: 10px solid #70b5e6ee;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-prof h3 {\r\n");
      out.write("    font-size: 36px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-prof p {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-prof .nav-tabs {\r\n");
      out.write("    border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .nav>li {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .nav>li>a {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .nav>li>a:focus,\r\n");
      out.write(".card .nav>li>a:hover {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    background-color: #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .s-nav>li>a.active {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    background-color: #3afe;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-blue {\r\n");
      out.write("    color: #3afe;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.friend-list {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.friend-list li {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.friend-list li:hover {\r\n");
      out.write("    background: rgba(0, 0, 0, .1);\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.friend-list .left img {\r\n");
      out.write("    width: 45px;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.friend-list li {\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.friend-list .right h3 {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul.friend-list .right p {\r\n");
      out.write("    font-size: 11px;\r\n");
      out.write("    color: #6c757d;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-timeline-card .dropdown-toggle::after {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-card h4 {\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-card h2 {\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-about .social-info {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-about p {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-card i {\r\n");
      out.write("    color: #3afe;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 300px;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    box-shadow: 0 10px 7px -5px rgba(0, 0, 0, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .header {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    background-color: #3afe;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .header::before,\r\n");
      out.write(".card-one .header::after {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    background: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .header::before {\r\n");
      out.write("    -webkit-transform: skewY(-8deg);\r\n");
      out.write("    transform: skewY(-8deg);\r\n");
      out.write("    -webkit-transform-origin: 100% 100%;\r\n");
      out.write("    transform-origin: 100% 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .header::after {\r\n");
      out.write("    -webkit-transform: skewY(8deg);\r\n");
      out.write("    transform: skewY(8deg);\r\n");
      out.write("    -webkit-transform-origin: 0 100%;\r\n");
      out.write("    transform-origin: 0 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .header .avatar {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    top: 30px;\r\n");
      out.write("    margin-left: -50px;\r\n");
      out.write("    z-index: 5;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    background: #ccc;\r\n");
      out.write("    border: 3px solid #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .header .avatar img {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    -webkit-transform: translate(-50%, -50%);\r\n");
      out.write("    transform: translate(-50%, -50%);\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one h3 {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin: 80px 0 30px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one h3::after {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: -15px;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    margin-left: -15px;\r\n");
      out.write("    width: 30px;\r\n");
      out.write("    height: 1px;\r\n");
      out.write("    background: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .desc {\r\n");
      out.write("    padding: 0 1rem 2rem;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    line-height: 1.5;\r\n");
      out.write("    color: #777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .contacts {\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    margin: 0 auto 3rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .contacts a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 33.333333%;\r\n");
      out.write("    float: left;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #c8c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .contacts a:hover {\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .contacts a:hover .fa::before {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .contacts a:hover .fa::after {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .contacts a .fa {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 40px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    line-height: 39px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 1.3em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .contacts a .fa:before {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .contacts a .fa::after {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 0;\r\n");
      out.write("    -webkit-transform: translate(-50%, -50%);\r\n");
      out.write("    transform: translate(-50%, -50%);\r\n");
      out.write("    background: #c8c;\r\n");
      out.write("    transition: width .3s, height .3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .contacts a:last-of-type .fa {\r\n");
      out.write("    line-height: 36px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .footer {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding: 1rem;\r\n");
      out.write("    background-color: #3afe;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .footer a {\r\n");
      out.write("    padding: 0 1rem;\r\n");
      out.write("    color: #e2e2e2;\r\n");
      out.write("    transition: color .4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .footer a:hover {\r\n");
      out.write("    color: #c8c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-one .footer::before {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -27px;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    margin-left: -15px;\r\n");
      out.write("    border: 15px solid transparent;\r\n");
      out.write("    border-bottom-color: #3afe;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-title, .card .card-title, .card-2 .card-title {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write(".badge {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    line-height: 1;\r\n");
      out.write("    padding: .375rem .5625rem;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".badge-primary {\r\n");
      out.write("    color: #447de8;\r\n");
      out.write("    background-color: #e6edff;\r\n");
      out.write("}\r\n");
      out.write(".badge {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: .4em .5em;\r\n");
      out.write("    font-size: 75%;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    line-height: 1;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    vertical-align: baseline;\r\n");
      out.write("    transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out, box-shadow .15s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("/*end social*/\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/lecture/lecture_home.jsp(33,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty lecture_info.profilepath  }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<!-- 프로필 이미지가 존재하지 않을 때 -->\r\n");
          out.write("	<img class='user-profile' src=\"img/testimonial-4.jpg\">\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/lecture/lecture_home.jsp(37,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty lecture_info.profilepath }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<img class='user-profile' src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lecture_info.profilepath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
