/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-26 00:56:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/teamB-project/WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1669102095569L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>mypage</title>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"css/member.css?");
      out.print(new java.util.Date());
      out.write("\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".my_info_in li strong, .my_info_in li span {\r\n");
      out.write("	color: #000;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"container\" class=\"ct_top\">\r\n");
      out.write("		<div class=\"main_wrap\">\r\n");
      out.write("			<h2 class=\"lnb_title text-center text-dark\">마이페이지</h2>\r\n");
      out.write("			<ul id=\"lnb\" class=\"lnb_list\">\r\n");
      out.write("				<li id=\"lnb_enrolment_log\"><a href=\"enrolment_log.me\"\r\n");
      out.write("					class=\"btn btn-outline-dark rounded-pill text-dark\"> 수강현황 </a></li>\r\n");
      out.write("				<li id=\"lnb_modify_myinfo\"><a href=\"modify_verify.me\"\r\n");
      out.write("					class=\"btn btn-outline-dark rounded-pill text-dark\"> 회원정보수정 </a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div id=\"contet_area\">\r\n");
      out.write("				<div class=\"content_body\">\r\n");
      out.write("					<div class=\"my_box\">\r\n");
      out.write("						<div class=\"my_info\">\r\n");
      out.write("							<h6>\r\n");
      out.write("								나의정보 <span class=\"h6_sub\">나의 정보를 확인하세요.</span>\r\n");
      out.write("							</h6>\r\n");
      out.write("							<ul class=\"my_info_in\">\r\n");
      out.write("								<li><strong>회원명</strong> <span class=\"name\">김하나</span></li>\r\n");
      out.write("								<li><strong>이메일</strong> <span>hana@naver.com</span></li>\r\n");
      out.write("								<li><strong>전화번호</strong> <span>010-1001-1001</span></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<span class=\"btn_more\"> <a href=\"modify_verify.me\"\r\n");
      out.write("								class=\"btn btn-dark text-white\"> 정보수정 </a>\r\n");
      out.write("							</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"my_note\">\r\n");
      out.write("							<h6>\r\n");
      out.write("								공지사항 <span class=\"h6_sub\">새로운 소식을 확인하세요.</span>\r\n");
      out.write("							</h6>\r\n");
      out.write("							<div class=\"my_notice_in\">\r\n");
      out.write("								<ul class=\"list_top\">\r\n");
      out.write("									<li><a href=\"#list\">계좌 환불 요청시 주의 사항</a></li>\r\n");
      out.write("									<li><a href=\"#list\">입금계좌 확인하는 법</a></li>\r\n");
      out.write("									<li><a href=\"#list\">결제 오류 및 계좌 입금 안내</a></li>\r\n");
      out.write("									<li><a href=\"#list\">쿠폰 등록 방법</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"enrolment_log_box\">\r\n");
      out.write("						<h5 class=\"tb_title\">\r\n");
      out.write("							수강 중인 과정 <span>(최근 수강시작일순 10개)</span>\r\n");
      out.write("						</h5>\r\n");
      out.write("						<div class=\"tb_box type_list mypage_course_user_list\">\r\n");
      out.write("							<table summary=\"수강 중인 과정 및 기간을 나타냅니다.\">\r\n");
      out.write("								<colgroup>\r\n");
      out.write("									<col style=\"width: 10%\">\r\n");
      out.write("									<col>\r\n");
      out.write("									<col style=\"width: 27%\">\r\n");
      out.write("									<col style=\"width: 13%\">\r\n");
      out.write("								</colgroup>\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"col\">구분</th>\r\n");
      out.write("										<th scope=\"col\">과정명</th>\r\n");
      out.write("										<th scope=\"col\">학습기간</th>\r\n");
      out.write("										<th scope=\"col\">강의실</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td class=\"tac\" colspan=\"5\">수강 중인 과정이 없습니다.</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"consulting_box\">\r\n");
      out.write("						<h5 class=\"tb_title\">상담</h5>\r\n");
      out.write("						<div class=\"tb_box type_list mypage_course_user_list\">\r\n");
      out.write("							<table summary=\"상담내역을 나타냅니다.\">\r\n");
      out.write("								<colgroup>\r\n");
      out.write("									<col>\r\n");
      out.write("									<col style=\"width: 30%\">\r\n");
      out.write("									<col style=\"width: 10%\">\r\n");
      out.write("								</colgroup>\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th scope=\"col\">제목</th>\r\n");
      out.write("										<th scope=\"col\">등록일</th>\r\n");
      out.write("										<th scope=\"col\">답변상태</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td class=\"tac\" colspan=\"5\">상담내역이 없습니다.</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
